export const challenges = {
  Original: [
    "Enemy Kills Themself on Tripwire",
    "Kill a Boss Knife-Only",
    "Grab the Free SQBR",
    "Kill Saddler Without a Rocket",
    "Get S rank with Ada (Mercs)",
    "Do Knight Room Without Flashes (Leon)",
    "Complete 3 Merchant Requests",
    "Kill 3 Enemies with 1 Flash",
    "Get S rank with Luis (Mercs)",
    "Kill 3 Rats with a Knife",
    "Kill the Verdugo (Leon)",
    "Buy an Exclusive Upgrade",
    "Kill Ashley",
    "Complete 5 Merchant Requests",
    "Complete an Entire Chapter Without Reloading (Not Ashley)",
    "Kill an Enemy with a Harpoon (Not DelLago)",
    "Throw a Golden Egg at Ashley",
    "Kill a Boss with only the Bolt-Thrower",
    "Complete an Entire Chapter Without Picking Anything Up (Not Ashley – Excludes Key Items)",
    "Get S rank with Leon (Mercs)",
    "Destroy 10 Medallions",
    "Craft a Full Crown (5 Colors)",
    "Avoid Killing Medieval Gigante",
    "Kill the Savage Mutt",
    "Get Attacked by a Chicken",
    "Have 200,000 ptas at one time",
    "Sell 3 different weapons",
    "Capture the Lunker Bass",
    // "Capture the Lord of the Waterway",
    "Craft a Full Necklace",
    "Watch any cutscene",
    "Die to Chainsaw Guy",
    "Get hit by a pig",
    "Get hit by cow",
    "Never use yellow herb in village",
    "Kill Regenerator without Bioscope",
    "Break 5 windows",
    "Own 30 spinels at one time",
    "Don't use rocket launcher in castle"
  ],
  ChatGPT: [
    "Kill 2 Enemies with One Grenade",
    "Parry a Chainsaw Attack",
    "Trade with the Merchant 5 Times in One Chapter",
    "Kill 5 Enemies Using Proximity Mines",
    "Complete a Chapter Without Using Healing Items",
    "Save the Merchant from an Enemy Attack",
    "Shoot a Snake Before It Bites",
    "Get a S+ Rank in a Shooting Gallery Challenge",
    "Sell 3 Treasures with Triple Bonuses",
    "Kill a Regenerador Using Only the Bolt Thrower",
    "Kill an Enemy with a Cannon",
    "Catch a Fish and Eat It",
    "Kill a Zealot With Their Own Catapult",
    "Disarm a Bear Trap Without Stepping In It",
    "Craft Bolts and Use Them in the Same Chapter",
    "Use a Flashbang to Kill a Plagas Mutant",
    "Kill an Enemy With a Barrel Explosion",
    "Kill an Armored Enemy With a Headshot",
    "Open Every Locked Drawer in One Playthrough",
    "Kill 10 Enemies Without Reloading",
    "Interrupt a Cultist Chant with a Gunshot",
    "Trade Spinels for a Map",
    "Jump Down Onto an Enemy and Kill Them Mid-Stagger"
  ]
};
